# Generated by Django 2.2.2 on 2021-07-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fan',
            field=models.BooleanField(default=True),
        ),
    ]
